; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ControllerV2]
platform = teensy
board = teensy41
framework = arduino
lib_deps = adafruit/Adafruit BNO08x@^1.2.5
build_flags = -Wno-switch -Isrc -Isrc/nativeethernet/ -Isrc/port/ -Isrc/port/compiler -Isrc/port/cpu -Isrc/port/netif/fec/ -Isrc/port/cpu/mimxrt -Isrc/service/ -Isrc/stack -Isrc/third_party -Isrc/third_party/mbedtls-2.12.0/src -Isrc/third_party/mbedtls-2.12.0/src/mbedtls
